### ISSUE TITLE
Ukkonen is misspelled throughout

### ISSUE THREAD

**Issue by tripleee** [jayrbolton/node-suffix-tree#1]
You will probably get more visitors if you fix the spelling of Mr. Ukkonen's last name in the repo's description on Github and in the code in the repo.

**Comment by jayrbolton** [comment]
Thanks @tripleee -- will definitely make the fix

**Comment by jayrbolton** [comment]
Pushed to master https://github.com/jayrbolton/node-suffix-tree/commit/9e3f4efe3145a789c551e3c4a7af7471d3d1de83

**Comment by tripleee** [comment]
Thanks for the quick update (-:

It's still misspelled in the repo's description on Github but I guess that's minor.

**Comment by jayrbolton** [comment]
Haha, at least I was v consistent.. fixed
